language: swift
osx_image: xcode8.3
xcode_workspace: NFLSers-iOS.xcworkspace
before_install:
   - sysctl -n machdep.cpu.brand_string
   - rvm install 2.2
   - rvm use 2.2
   - sudo gem install activesupport -v 4.2.6
   - sudo gem install cocoapods -v '1.2.1'  
