language: swift
osx_image: xcode9
xcode_workspace: NFLSers-iOS.xcworkspace
before_install:
   - sysctl -n machdep.cpu.brand_string
   - rvm install 2.2
   - rvm use 2.2
   - sudo gem install activesupport -v 4.2.6
   - sudo gem install cocoapods -v '1.3.1'
   - pod repo update
script:
   - xcodebuild -workspace NFLSers-iOS.xcworkspace -list
   - xcodebuild clean build -workspace NFLSers-iOS.xcworkspace -scheme NFLSers-iOS CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO  
