# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
  	xcclean(workspace: "NFLSers-iOS.xcworkspace", scheme: "NFLSers-iOS")
    build_app(workspace: "NFLSers-iOS.xcworkspace", scheme: "NFLSers-iOS")
    changelog_from_git_commits
    upload_to_testflight(skip_waiting_for_build_processing: true)
  end
  desc "Upload debug files to Sentry"
  lane :sentry do
    download_dsyms(version:"1.2.19", output_directory: "dsyms")
  end
end
