# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
  	xcclean(workspace: "NFLSers-iOS.xcworkspace", scheme: "NFLSers-iOS")
  	changelog_from_git_commits
    #increment_build_number(xcodeproj: "NFLSers-iOS.xcodeproj")
    build_app(workspace: "NFLSers-iOS.xcworkspace", scheme: "NFLSers-iOS")
    upload_to_testflight
  end
end
